"""
This type stub file was generated by pyright.
"""

class MQTTMatcher:
    """Intended to manage topic filters including wildcards.

    Internally, MQTTMatcher use a prefix tree (trie) to store
    values associated with filters, and has an iter_match()
    method to iterate efficiently over all filters that match
    some topic name."""
    class Node:
        __slots__ = ...
        def __init__(self) -> None:
            ...
        
    
    
    def __init__(self) -> None:
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Add a topic filter :key to the prefix tree
        and associate it to :value"""
        ...
    
    def __getitem__(self, key):
        """Retrieve the value associated with some topic filter :key"""
        ...
    
    def __delitem__(self, key): # -> None:
        """Delete the value associated with some topic filter :key"""
        ...
    
    def iter_match(self, topic): # -> Generator[Any, Any, None]:
        """Return an iterator on all values associated with filters
        that match the :topic"""
        ...
    


